class CreateCastles < ActiveRecord::Migration
  def change
    create_table :castles do |t|
    t.boolean "approved", :default => false
    t.integer "user_id"
    t.string  "castle_name_en"
    t.string  "castle_name_ja"
    t.string  "castle_name_r"
    t.boolean "has_ishigaki"
    t.boolean "has_buildings"
    t.string  "kamon"
    t.string  "kamon_fam"
    t.string  "castle_name_alt"
    t.string  "founder"
    t.string  "year"
    t.string  "year_reconstructed"
    t.string  "castle_type"
    t.string  "structure"
    t.string  "artifacts"
    t.string  "location"
    t.string  "clongitude"
    t.string  "clatitude"
    t.integer "gmapicn"
    t.string  "access"
    t.string  "website"
    t.string  "pro_web_name"
    t.string  "visited"
    t.text    "notes"
    t.text    "history"
    t.text    "shortdesc"
    t.string  "condition"
    t.string  "prefecture"
    t.string  "historical_value"
    t.string  "rating"
    t.string  "year_visited"
    t.string  "top_100"
    t.string  "has_NT"
    t.string  "has_ICP"
    t.string  "destination"
    t.string  "unesco"
    t.string  "period"
    t.integer "bestZoom"
    t.string  "bestMap"
    t.decimal "rating_average", :precision => 6, :scale => 2, :default => 0.0
    t.text    "notesJse"
    t.boolean "manualUpdate"
    t.string  "ekiLatLng"
    t.integer "ekiElev"
    t.integer "castleElev"
    t.integer "elevChange"
    t.string  "timeRequired"
    t.text    "visitorInfo"
    t.timestamps
    end
  end
end
